from typing import List, Optional
from pydantic import BaseModel, Field

class LogSignature(BaseModel):
    """Output model for the Diagnostic Agent parsing raw logs."""
    service_name: str = Field(description="Name of the affected microservice or component")
    severity: str = Field(description="Incident severity level (e.g., CRITICAL, HIGH, MEDIUM, LOW)")
    error_signature: str = Field(description="Core error pattern, exception message, or exit code extracted from logs")
    query_string: str = Field(description="Optimized search query generated to search vector runbooks")

class RemediationPlan(BaseModel):
    """Final structured incident report generated by the Resolution Agent."""
    service_name: str = Field(description="Affected microservice name")
    severity: str = Field(description="Assessed severity level")
    root_cause: str = Field(description="Detailed explanation of the underlying root cause")
    immediate_fixes: List[str] = Field(description="Step-by-step immediate mitigation actions")
    preventative_actions: List[str] = Field(description="Long-term preventative recommendations")
    confidence_score: float = Field(description="Confidence rating between 0.0 and 1.0 based on available runbook context")

class AgentState(BaseModel):
    """LangGraph state schema passing context through nodes."""
    raw_logs: str
    log_signature: Optional[LogSignature] = None
    retrieved_docs: List[str] = Field(default_factory=list)
    final_report: Optional[RemediationPlan] = None